const translations = {
    he: {
        app: {
            title: "הכסף שלי",
        },
        welcome: {
            subtitle: "ניהול פיננסי חכם וקל",
            guest_button: "התחל כאורח",
            or_login: "או התחבר/הירשם",
        },
        login: {
            email: "אימייל",
            password: "סיסמה",
            login_button: "התחבר",
            google_login: "התחבר עם Google",
            no_account: "אין לך חשבון?",
            register_here: "הירשם כאן",
        },
        register: {
            email: "אימייל",
            password: "סיסמה",
            confirm_password: "אישור סיסמה",
            register_button: "הרשם",
            has_account: "יש לך כבר חשבון?",
            login_here: "התחבר כאן",
        },
        nav: {
            home: "בית",
            budget: "ניהול כסף",
            graphs: "גרפים",
            settings: "הגדרות",
        },
        home: {
            greeting_user: "שלום,",
            greeting_guest: "שלום, אורח!",
            current_balance: "יתרה נוכחית",
            financial_goals: "יעדים פיננסיים",
            goal_target: "יעד",
            add_goal_button: "הוסף יעד",
            goal_name_placeholder: "שם היעד",
            goal_amount_placeholder: "סכום היעד",
            save_goal_button: "שמור יעד",
            delete_button: "מחק",
            notifications_title: "התראות",
            enable_notifications_button: "אפשר התראות",
        },
        budget: {
            title: "ניהול כסף",
            current_balance: "יתרה נוכחית",
            add_transaction_title: "הוספת פעולה",
            transaction_type_label: "סוג פעולה:",
            transaction_type_income: "הכנסה",
            transaction_type_expense: "הוצאה",
            currency_label: "מטבע:",
            amount_label: "סכום:",
            amount_placeholder: "סכום",
            description_label: "תיאור (אופציונלי):",
            description_placeholder: "תיאור הפעולה",
            date_label: "תאריך:",
            add_transaction_button: "הוסף פעולה",
            history_title: "היסטוריית פעולות",
            toggle_table_button: "הצג/הסתר טבלה",
            filter_from: "מתאריך:",
            filter_to: "עד תאריך:",
            filter_button: "סנן",
            reset_filter_button: "אפס סינון",
            table_date: "תאריך",
            table_amount: "סכום (מטבע מקור)",
            table_type: "סוג",
            table_description: "תיאור",
            table_actions: "פעולות",
            delete_button: "מחק",
            summary_title: "סיכום תקופה",
            summary_income: "הכנסות:",
            summary_expense: "הוצאות:",
            summary_balance: "מאזן:",
            summary_good: "כל הכבוד! נשאר לך עודף בתקופה זו.",
            summary_neutral: "סיימת את התקופה באיזון.",
            summary_bad: "שים לב, נכנסת למינוס בתקופה זו.",
        },
        graphs: {
            title: "גרפים",
            expenses_by_category: "הוצאות לפי קטגוריות",
            other_category: "אחר",
        },
        settings: {
            title: "הגדרות",
            profile_title: "פרופיל",
            email_label: "אימייל",
            guest_email: "אורח",
            password_label: "סיסמה:",
            show_password: "הצג",
            hide_password: "הסתר",
            logout_button: "התנתק",
            theme_title: "ערכת נושא ועיצוב",
            theme_light: "נושא בהיר",
            theme_dark: "נושא כהה",
            main_color_label: "צבע ראשי:",
            accent_color_label: "צבע משני:",
            font_label: "פונט:",
            currency_title: "הגדרות מטבע",
            base_currency_label: "מטבע בסיס:",
            language_title: "שפה",
            language_label: "בחר שפה:",
        },
        messages: {
            password_mismatch: "הסיסמאות אינן תואמות!",
            register_success: "הרשמה מוצלחת! אתה מחובר כעת.",
            register_error: "שגיאת הרשמה",
            login_success: "התחברות מוצלחת!",
            login_error: "שגיאת התחברות",
            google_login_success: "התחברות עם גוגל מוצלחת!",
            google_login_error: "שגיאת התחברות עם גוגל",
            fill_amount_date: "אנא מלא סכום ותאריך",
            transaction_added: "פעולה נוספה בהצלחה!",
            transaction_deleted: "פעולה נמחקה בהצלחה.",
            fill_goal_details: "אנא מלא שם וסכום ליעד",
            goal_added: "יעד נוסף בהצלחה!",
            goal_deleted: "יעד נמחק בהצלחה.",
            select_date_range: "אנא בחר תאריכי התחלה וסיום.",
            notifications_enabled: "התראות מופעלות. 🎉",
            notifications_can_enable: "ניתן לאפשר התראות לאפליקציה!",
            notifications_pwa_only: "התראות זמינות רק כאשר האתר מותקן כאפליקציה.",
            notifications_granted: "התראות אושרו! 🎉",
            notifications_enabled_message: "התראות אפליקציה הופעלו בהצלחה!",
            notifications_denied: "התראות נדחו. 😔",
            notifications_not_supported: "התראות לא נתמכות בדפדפן זה.",
        },
        currencies: {
            "ILS": "₪ - שקל ישראלי",
            "USD": "$ - דולר אמריקאי",
            "EUR": "€ - אירו",
            "GBP": "£ - לירה שטרלינג",
        }
    },
    en: {
        app: {
            title: "My Money",
        },
        welcome: {
            subtitle: "Smart and easy financial management",
            guest_button: "Start as a Guest",
            or_login: "Or login/register",
        },
        login: {
            email: "Email",
            password: "Password",
            login_button: "Login",
            google_login: "Login with Google",
            no_account: "Don't have an account?",
            register_here: "Register here",
        },
        register: {
            email: "Email",
            password: "Password",
            confirm_password: "Confirm Password",
            register_button: "Register",
            has_account: "Already have an account?",
            login_here: "Login here",
        },
        nav: {
            home: "Home",
            budget: "Budget",
            graphs: "Graphs",
            settings: "Settings",
        },
        home: {
            greeting_user: "Hello,",
            greeting_guest: "Hello, Guest!",
            current_balance: "Current Balance",
            financial_goals: "Financial Goals",
            goal_target: "Target",
            add_goal_button: "Add Goal",
            goal_name_placeholder: "Goal Name",
            goal_amount_placeholder: "Goal Amount",
            save_goal_button: "Save Goal",
            delete_button: "Delete",
            notifications_title: "Notifications",
            enable_notifications_button: "Enable Notifications",
        },
        budget: {
            title: "Budget Management",
            current_balance: "Current Balance",
            add_transaction_title: "Add Transaction",
            transaction_type_label: "Type:",
            transaction_type_income: "Income",
            transaction_type_expense: "Expense",
            currency_label: "Currency:",
            amount_label: "Amount:",
            amount_placeholder: "Amount",
            description_label: "Description (optional):",
            description_placeholder: "Transaction Description",
            date_label: "Date:",
            add_transaction_button: "Add Transaction",
            history_title: "Transaction History",
            toggle_table_button: "Show/Hide Table",
            filter_from: "From Date:",
            filter_to: "To Date:",
            filter_button: "Filter",
            reset_filter_button: "Reset Filter",
            table_date: "Date",
            table_amount: "Amount (Original Currency)",
            table_type: "Type",
            table_description: "Description",
            table_actions: "Actions",
            delete_button: "Delete",
            summary_title: "Period Summary",
            summary_income: "Income:",
            summary_expense: "Expenses:",
            summary_balance: "Balance:",
            summary_good: "Great job! You have a surplus in this period.",
            summary_neutral: "You finished this period in balance.",
            summary_bad: "Warning, you have a deficit in this period.",
        },
        graphs: {
            title: "Graphs",
            expenses_by_category: "Expenses by Category",
            other_category: "Other",
        },
        settings: {
            title: "Settings",
            profile_title: "Profile",
            email_label: "Email",
            guest_email: "Guest",
            password_label: "Password:",
            show_password: "Show",
            hide_password: "Hide",
            logout_button: "Logout",
            theme_title: "Theme and Design",
            theme_light: "Light Theme",
            theme_dark: "Dark Theme",
            main_color_label: "Main Color:",
            accent_color_label: "Accent Color:",
            font_label: "Font:",
            currency_title: "Currency Settings",
            base_currency_label: "Base Currency:",
            language_title: "Language",
            language_label: "Choose Language:",
        },
        messages: {
            password_mismatch: "Passwords do not match!",
            register_success: "Registration successful! You are now logged in.",
            register_error: "Registration Error",
            login_success: "Login successful!",
            login_error: "Login Error",
            google_login_success: "Google login successful!",
            google_login_error: "Google login Error",
            fill_amount_date: "Please fill in amount and date",
            transaction_added: "Transaction added successfully!",
            transaction_deleted: "Transaction deleted successfully.",
            fill_goal_details: "Please fill in goal name and amount",
            goal_added: "Goal added successfully!",
            goal_deleted: "Goal deleted successfully.",
            select_date_range: "Please select a date range.",
            notifications_enabled: "Notifications are enabled. 🎉",
            notifications_can_enable: "You can enable notifications for the app!",
            notifications_pwa_only: "Notifications are only available when the site is installed as a PWA.",
            notifications_granted: "Notifications granted! 🎉",
            notifications_enabled_message: "App notifications have been successfully enabled!",
            notifications_denied: "Notifications denied. 😔",
            notifications_not_supported: "Notifications are not supported in this browser.",
        },
        currencies: {
            "ILS": "₪ - Israeli New Shekel",
            "USD": "$ - US Dollar",
            "EUR": "€ - Euro",
            "GBP": "£ - Pound Sterling",
        }
    }
};

export default translations;